[package]
name = "attendance-management-actix-web-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
chrono = { version = "0.4", features = ["serde"]}
serde = { version = "1.0", features = ["derive"]}
uuid = { version = "1.0", features = ["v4", "serde"]}
thiserror = "2.0"
