version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: attendance_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d attendance_test"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: